classdef project_2dgs_fused < deep.DifferentiableFunction
    properties
        Format;
    end

    methods
        function fcn = project_2dgs_fused(format)
            output_num = 5; % important!!!

            fcn@deep.DifferentiableFunction(output_num,...
                            SaveInputsForBackward = true,...
                            SaveOutputsForBackward = false,...
                            NumMemoryValues = 2);

            fcn.Format = string(format);
        end
        
        %% forward function
        function [xys, ...
                  depths, ...
                  radii,...
                  conics, ...
                  num_tiles_hit,...
                  memo1,memo2] = forward(~,xy_pos, ...
                                            rotation, ...
                                            scales, ...
                                            img_sz)
            [xys, ...
             depths,...
             radii,...
             conics,...
             num_tiles_hit...
             ] = fullyfused_2dgs_projection(...
                     'fwd',...
                     xy_pos,...
                     rotation,...
                     scales,...
                     uint32(gather(img_sz)));
            
            memo1 = radii;
            memo2 = conics;
        end
        
        %% backward function
        function [dl_dxy_pos,...
                  dl_drot,...
                  dl_dscales,...
                  dl_dimg_sz] = backward(~,dl_dxy, ...
                                            dl_ddepths, ...
                                            ~, ...          %dl_dradii
                                            dl_dconics, ...
                                            ~, ...          %dl_dnum_tiles_hit
                                            ~, ...          %computeGradients
                                            xy_pos, ...
                                            rotation, ...
                                            scales, ...
                                            img_sz, ...
                                            memo1,memo2)

            dl_dimg_sz = [];

            [~,...
                dl_dxy_pos, ...
                dl_drot, ...
                dl_dscales...
            ] = fullyfused_2dgs_projection(...
                'bwd', ...
                xy_pos, ...
                rotation, ...
                scales, ...
                memo1, memo2, ...
                dl_dxy, ...
                dl_ddepths, ...
                dl_dconics, ...
                uint32(gather(img_sz)) ...
            );
            
        end
    end


end