classdef project_2dgs_fused < deep.DifferentiableFunction
    properties
        Format;
    end

    methods
        function fcn = project_2dgs_fused(format)
            output_num = 5; % important!!!

            fcn@deep.DifferentiableFunction(output_num,...
                            SaveInputsForBackward = false,...
                            SaveOutputsForBackward = false,...
                            NumMemoryValues = 1);

            fcn.Format = string(format);
        end
        
        %% forward function
        function [xys, ...
                  depths, ...
                  radii,...
                  conics, ...
                  num_tiles_hit,...
                  memo] = forward(~,xy_pos,...
                                             rotation,...
                                             scales,...
                                             img_sz)
   
            [xys, ...
             depths,...
             radii,...
             conics,...
             num_tiles_hit...
             ] = mex.fused_2dgs_project_forward(...
                     xy_pos,...
                     rotation,...
                     scales,...
                     uint32(gather(img_sz)));
            
            memo.xy_pos = xy_pos;
            memo.rotation = rotation;
            memo.scales = scales;
            memo.img_sz = img_sz;

      
            memo.radii = radii;
            memo.conics = conics;
        end
        
        %% backward function
        function [dl_dxy_pos,...
                  dl_drot,...
                  dl_dscales,...
                  dl_dimg_sz] = backward(~,dl_dxy,...
                                            dl_ddepths,...
                                            dl_dradii,...
                                            dl_dconics,...
                                            dl_dnum_tiles_hit,...
                                            computeGradients,...
                                            memo)
            dl_dimg_sz = [];

            [~,...
                dl_dxy_pos, ...
                dl_drot, ...
                dl_dscales...
            ] = mex.fused_2dgs_project_backward(...
                memo.xy_pos,...
                memo.rotation,...
                memo.scales,...
                memo.radii,...
                memo.conics,...
                dl_dxy,...
                dl_ddepths,...
                dl_dconics,...
                uint32(gather(memo.img_sz))...
            );
            clear memo;
        end
    end


end