classdef rasterize_2dgs_fused < deep.DifferentiableFunction
    properties
        Format;
    end

    methods
        function fcn = rasterize_2dgs_fused(format)
            output_num = 1; % important!!!

            fcn@deep.DifferentiableFunction(output_num,...
                            SaveInputsForBackward = false,...
                            SaveOutputsForBackward = false,...
                            NumMemoryValues = 1);

            fcn.Format = string(format);
        end
        
        %% forward function
        function [canvas,memo] = forward(~,xys,...
                                             depths,...
                                             radii,...
                                             conics,...
                                             num_tiles_hit,...
                                             colors,...
                                             opacity,...
                                             img_sz)
    

            [cum_tiles_hit,...
             num_intersec] = compute_cumulative_intersects(num_tiles_hit);



            % calculation the intersection
            [isect_ids,...
             gauss_ids] = mex.fused_2dgs_map_tointersects(...
                gather(num_intersec),...
                xys,...
                depths,...
                radii,...
                cum_tiles_hit,...
                uint32(gather(img_sz))...
            );


            [isect_ids_sorted,sorted_indices] = sort(isect_ids);
            gaussian_ids_sort = gauss_ids(sorted_indices);

            tile_bins = mex.fused_get_tilebin_edges(isect_ids_sorted);

            % fast gaussian splatting rasterization
            [canvas,...
               final_idx] = mex.fused_2dgs_rasterize_forward(xys,...
                                                conics,...
                                                colors,...
                                                opacity,...
                                                gaussian_ids_sort,...
                                                tile_bins,...
                                                uint32(gather(img_sz)));

            % save for backward
            memo.final_idx    = final_idx;
            memo.gauss_ids    = gaussian_ids_sort;
            memo.tile_bins    = tile_bins;
            memo.xys          = xys;
            memo.conics       = conics;
            memo.colors       = colors;
            memo.opacity      = opacity;
            memo.img_sz       = img_sz;
            memo.num_intersec = num_intersec;
        end

        %% backward function
        function [dl_dxys,...
                  dl_ddepths,...
                  dl_dradii,...
                  dl_dconics,...
                  dl_dnum_tiles_hit,...
                  dl_dcolors,...
                  dl_dopacity,...
                  dl_dimg_sz] = backward(~,dl_canvas,...
                                           computeGradients,...
                                           memo)
            

            dl_ddepths = [];
            dl_dradii = [];
            dl_dnum_tiles_hit = [];
            dl_dimg_sz = [];


            if memo.num_intersec < 1
                dl_dxys     = gpuArray(zeros(size(memo.xys),'single'));
                dl_dconics  = gpuArray(zeros(size(memo.conics),'single'));
                dl_dcolors  = gpuArray(zeros(size(memo.colors),'single'));
                dl_dopacity = gpuArray(zeros(size(memo.opacity),'single'));
            else
                [dl_dxys, dl_dconics, dl_dcolors, dl_dopacity] = ...
                mex.fused_2dgs_rasterize_backward(...
                    memo.gauss_ids,...
                    memo.tile_bins,...
                    memo.xys,...
                    memo.conics,...
                    memo.colors,...
                    memo.opacity,...
                    memo.final_idx,...
                    2 * real(dl_canvas),...
                    uint32(gather(memo.img_sz))...
                );
            end
            clear memo;
        end


    end
end


function [cum_tiles_hit,num_intersects] = ...
                              compute_cumulative_intersects(num_tiles_hit)

    cum_tiles_hit = cumsum(num_tiles_hit);

    num_intersects = cum_tiles_hit(end);
end
