classdef rasterize_2dgs_fused < deep.DifferentiableFunction
    properties
        Format;
    end

    methods
        function fcn = rasterize_2dgs_fused(format)
            output_num = 1; % important!!!

            fcn@deep.DifferentiableFunction(output_num,...
                            SaveInputsForBackward = true,...
                            SaveOutputsForBackward = false,...
                            NumMemoryValues = 4);

            fcn.Format = string(format);
        end
        
        %% forward function
        function [canvas, ...
                  ... % ctxs
                  final_idx, ...
                  gaussian_ids_sort, ...
                  tile_bins, ...
                  num_intersec] = forward(~,xys,...
                                             depths,...
                                             radii,...
                                             conics,...
                                             num_tiles_hit,...
                                             colors,...
                                             opacity,...
                                             img_sz)
    

            [cum_tiles_hit,...
             num_intersec] = compute_cumulative_intersects(num_tiles_hit);

            % calculation the intersection
            [isect_ids,...
             gauss_ids] = fused_2dgs_map_tointersects(...
                gather(num_intersec),...
                xys,...
                depths,...
                radii,...
                cum_tiles_hit,...
                uint32(gather(img_sz))...
            );

            [isect_ids_sorted,sorted_indices] = sort(isect_ids);
            gaussian_ids_sort = gauss_ids(sorted_indices);

            tile_bins = fused_get_tilebin_edges(isect_ids_sorted);

            % fast gaussian splatting rasterization
            [canvas,...
               final_idx] = fullyfused_2dgs_rasterization(...
                        'fwd', ...
                         xys, ...
                        conics, ...
                        colors, ...
                        opacity, ...
                        gaussian_ids_sort, ...
                        tile_bins, ...
                        uint32(gather(img_sz)));

        end

        %% backward function
        function [dl_dxys, ...
                  dl_ddepths, ...
                  dl_dradii, ...
                  dl_dconics, ...
                  dl_dnum_tiles_hit, ...
                  dl_dcolors, ...
                  dl_dopacity, ...
                  dl_dimg_sz] = backward(~,dl_canvas, ...
                                           ~, ... % computeGradients
                                           xys, ...
                                           ~, ... % depths
                                           ~, ... % radii
                                           conics, ...
                                           ~, ... % num_tiles_hit
                                           colors, ...
                                           opacity, ...
                                           img_sz, ...
                                           final_idx, ...
                                           gaussian_ids_sort, ...
                                           tile_bins, ...
                                           num_intersec)
            

            dl_ddepths = [];
            dl_dradii = [];
            dl_dnum_tiles_hit = [];
            dl_dimg_sz = [];

            if num_intersec < 1
                dl_dxys     = gpuArray(zeros(size(xys),'single'));
                dl_dconics  = gpuArray(zeros(size(conics),'single'));
                dl_dcolors  = gpuArray(zeros(size(colors),'single'));
                dl_dopacity = gpuArray(zeros(size(opacity),'single'));
            else
                [dl_dxys, ...
                 dl_dconics, ...
                 dl_dcolors, ...
                 dl_dopacity] = ...
                 ...
                 fullyfused_2dgs_rasterization(...
                    'bwd',...
                    gaussian_ids_sort,...
                    tile_bins,...
                    xys,...
                    conics,...
                    colors,...
                    opacity,...
                    final_idx,...
                    2 * real(dl_canvas),...
                    uint32(gather(img_sz))...
                );
            end
        end


    end
end


function [cum_tiles_hit,num_intersects] = ...
                              compute_cumulative_intersects(num_tiles_hit)

    cum_tiles_hit = cumsum(num_tiles_hit);

    num_intersects = cum_tiles_hit(end);
end
